yarnPath: .yarn/releases/yarn-3.6.3.cjs
packageExtensions:
  "@typedorm/core@*":
    peerDependencies:
      "@aws-sdk/lib-dynamodb": "^3.31.0"
    peerDependenciesMeta:
      aws-sdk:
        optional: true
  "@typedorm/document-client@*":
    peerDependenciesMeta:
      aws-sdk:
        optional: true
  "@aws-sdk/lib-dynamodb@*":
    dependencies:
      "@smithy/smithy-client": "^2.1.3"

